# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true # set to 'true' to leave the OAuth token in the Git config after the initial fetch

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod --base-href="https://preprod.lydiaetpaul2020.fr/" --output-path="$(Build.ArtifactStagingDirectory)"
    #ng build --prod --output-path="$(Build.ArtifactStagingDirectory)"
  displayName: 'npm install and build'

- script: |
    cd $(Build.Repository.LocalPath)
    git checkout gh-pages
  displayName: 'Switching to gh-pages Branch'

- script: |
    cd $(Build.Repository.LocalPath);
    git rm -rf .; git clean -fxd;
    touch README.md;
    echo "# Préproduction site de mariage" >> README.md;
    touch CNAME;
    echo "preprod.lydiaetpaul2020.fr" >> CNAME 
  displayName: 'Clean gh-pages Branch'

- script: |
    git config --global user.email "42136778+pfauchet@users.noreply.github.com";
    git config --global user.name "pfauchet";
  displayName: 'Configure Git User'

- script: |
    cp -r $(Build.ArtifactStagingDirectory)/* $(Build.Repository.LocalPath)
  displayName: 'Copy Artifact Files to gh-pages Branch'

- script: |
    cd $(Build.Repository.LocalPath)
    cp index.html 404.html
  displayName: 'Create 404.html file'

- script: >
    cd $(Build.Repository.LocalPath);
    git add --all;
    git commit -m"Pipelines-Bot: Updated site via $(Build.SourceVersion)";
    git push origin gh-pages
  displayName: 'Create our Commit'

# Note: github_pat should be configured as an environment variable in devops
#   -> create github pat here: https://github.com/settings/tokens
#   -> Create environment variable in dev.azure.com under pipelines -> edit (right top) -> variables (right top triple dots) -> called github_pat -> click the lock
- script: |
    gh_user="pfauchet";
    gh_pass=$(github_patv2);
    gh_repo="mariage";
    auth_pass=$(echo -n "${gh_user}:$(gh_pass)" | base64);
    
    curl https://api.github.com/repos/${gh_user}/${gh_repo}/pages/builds -I \
      -X POST \
      -H "Accept: application/vnd.github.mister-fantastic-preview+json" \
      -H "Authorization: Basic ${auth_pass}" -v
  displayName: '[GitHub] Trigger Page Build'

- script: |
    gh_user="thebillkidy";
    gh_pass=$(github_patv2);
    gh_repo="thebillkidy.github.io";
    auth_pass=$(echo -n "${gh_user}:$(gh_pass)" | base64);

    curl https://api.github.com/repos/${gh_user}/${gh_repo}/pages/builds/latest -I \
    -X GET \
    -H "Accept: application/vnd.github.mister-fantastic-preview+json" \
    -H "Authorization: Basic $auth_pass" -v
  displayName: '[GitHub] Get Page Build Status'